### ISSUE TITLE
Interaction with another xarray accessor

### ISSUE THREAD

**Issue by kthyng** [xarray-contrib/cf-xarray#101]
Sorry that I have more requests than things to give currently.

I've just written an accessor to choose the colormap for a plot based on metadata in the DataArray being plotted.

https://github.com/kthyng/xcmocean

The thing is, I want to use it with cf-xarray! Any idea how I can modify xcmocean or cf-xarray to do this? Here is what I want to be able to do:

```
import xcmocean
import xarray as xr

loc = 'http://barataria.tamu.edu:8080/thredds/dodsC/forecast_latest/txla2_his_f_latest.nc'
chunks = {'ocean_time':1}
ds = xr.open_dataset(loc, chunks=chunks)

# want cf to allow me to use `x='longitude', y='latitude'`
# want cmo to choose a temperature-appropriate colormap for the plot.
ds.temp.cf.cmo.plot(x='longitude', y='latitude')
```

The [important part](https://github.com/kthyng/xcmocean/blob/main/xcmocean/accessor.py#L26) of xcmocean is this inside the accessor:
```
    def plot(self, *args, **kwargs):
        with xr.set_options(cmap_sequential=self.seq, cmap_divergent=self.div):   
            self.da.plot(*args, **kwargs)
```

Thanks for any ideas!

**Comment by dcherian** [comment]
I have to think of this. It would be nice to support `hvplot` accessors for example.

my first thought is that xcmocean should provide a context manager but that's a lot of typing...

``` python
with xcmocean.colormaps():
    ds.temp.cf.plot(...)
```

The other option is that `xcmocean` could provde a `cfplot` class that just forwards to `.cf.plot`. This may be the best option. It's a little annoying to write (supporting both `.plot()` and `.plot.pcolormesh`), but seems most direct.

**Comment by kthyng** [comment]
I did the second idea and it worked easily:
![image](https://user-images.githubusercontent.com/3487237/95393532-653a6180-08c0-11eb-9918-94445e174955.png)

Is there a reason to wrap .plot and plot.pcolormesh both? They seem to be the same thing when plotting lon x lat x variable, which is the scenario for using a colormap.

**Comment by dcherian** [comment]
What if you wanted `.plot.contourf`?

**Comment by kthyng** [comment]
@dcherian But since you can input "levels" into the `plot` command to change to discrete color ranges, and with `infer_intervals` change the position of the x/y coordinates relative to the variable coordinates, can't you essentially get both pcolormesh and contourf from the same plot command?

**Comment by dcherian** [comment]
Hah OK. What about `.plot.contour`

**Comment by kthyng** [comment]
ok fine, you got me. I can wrap all three specifically. :) Just pushed this to github.

**Comment by kthyng** [comment]
Let me know if you think of another approach, but I'm fine with this for now.
