### ISSUE TITLE
How to get all variables with the same standard name?

### ISSUE THREAD

**Issue by malmans2** [xarray-contrib/cf-xarray#109]
A few times I needed to get the name of all coordinates with the same standard name.
Did I miss a public way to do this? Otherwise, the easiest thing I could come up with is this: 
```python
cf_xarray.accessor.apply_mapper(cf_xarray.accessor._get_axis_coord, ds, standard_name)
```

If there isn't a public function to do this already, maybe it could be helpful. For regular variables it seems easier, as it can be done through xarray:
```python
ds.cf[[standard_name]].data_vars
```

**Comment by dcherian** [comment]
You could do `ds.cf[[standard_name]].coords` but yes we need some API to expose all the "mappers" (#18).

Maybe 
```
ds.cf.get_names(standard_name=None, axis=None, coordinate=None, measure=None) -> List[str]
``` 

where `axis is in ["X", "Y", "Z", "T"]` and `coordinate is in ["latitude", "longitude", "vertical", "time"]` and `measure is in ["area", "volume"]`

What do we do when multiple kwargs are not None; apply an OR condition, or AND?

I don't think there's a similar function in xarray/pandas/python (except `filter_by_attrs`): I didn't see anything similar during a quick scan through Iris and cf-python's API (can you double check?)

cc @kthyng

**Comment by dcherian** [comment]
We could also change `.axes` `.coordinates`, `.standard_names`, and `.cell_measures` to return dicts mapping "standard name" to variable name. I think I may prefer this actually.

**Comment by malmans2** [comment]
`ds.cf[[standard_name]].coords` would not give me just the coordinates I'm looking for, but probably I don't have the best setup in the first place.
Anyway, I also think it would be better to get dictionaries out of `.axes`, etc... (which to me is what `describe()` is kind of suggesting).
I should be able to draft a PR tomorrow!
