### ISSUE TITLE
Show and allow indexing by extra cell measures

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#116]
As follow on from #115, it would be good to show arbitrary cell measures in `.cf.describe` and `.cf.cell_measures`. I think this would take some effort.

**Comment by malmans2** [comment]
> As follow on from #115, it would be good to show arbitrary cell measures in `.cf.describe` and `.cf.cell_measures`. 

Yes, I think this is going to be helpful, as right now I end up using the util function to parse the cell measures attribute.

> I think this would take some effort.

OK, I didn't expect it, so I'm probably overlooking something important. I'll have a look later this week!
