### ISSUE TITLE
Documentation build failed

### ISSUE THREAD

**Issue by malmans2** [xarray-contrib/cf-xarray#119]
Looks like readthedocs failed when we merged the latest branch.
See: https://readthedocs.org/projects/cf-xarray/builds/12477949/

Although I get a bunch of warnings, the documentation is compiling on my local machine.
The readthedocs build doesn't even show a log and says:
```
Error
There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (12477949).
```

Maybe it is enough to trigger another build? Looks like I don't have the permissions on readthedocs, so @dcherian might have to do it.

**Comment by dcherian** [comment]
I restarted it.

Whats your RTD username?

**Comment by malmans2** [comment]
> I restarted it.

Thanks!

> Whats your RTD username?

Should be connected to my GitHub account, so malmans2

**Comment by dcherian** [comment]
Ok you're on it now! and the build worked! Thanks for catching that.
