### ISSUE TITLE
How to figure out if there is a vertical dimension

### ISSUE THREAD

**Issue by allibco** [xarray-contrib/cf-xarray#123]
I am trying to figure out how best to see if I have a 2d or 3D variable - but if I check the vertical coordinate and there isn't one, then i get an error.  My work around is to put it in a `try except `block, but it could be nicer to return `None `or something...

![cam_ts](https://user-images.githubusercontent.com/14944423/105375545-07f3c300-5bc6-11eb-8494-0c507da8c195.png)

**Comment by aulemahal** [comment]
Hi!

I can suggest a few ways to do this check:
```python
# Through coords:
cam_ts.cf.coordinates.get('vertical')  # Returns the coord if present, None otherwise.
# Boolean check
'vertical' in cam_ts.cf   # True if there is one, False otherwise
```

Does this solve your problem?

I think accessing a dict-like object with the bracket [ ]  notation should return an error when the key is not present, to be coherent with "real" dictionaries. However, we could indeed have a `cam_ts.cf.get('vertical', default_value)` method, like a dictionary. While there are already other ways to do the same, it shouldn't be hard to implement and I don't see any issue with adding this.
We are always accepting new PRs if you have time!

**Comment by allibco** [comment]
Thanks much - this solves my problem!
