### ISSUE TITLE
Add a method to extract a variable along with associated CF variables.

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#126]
``` python
import cf_xarray as cf
import numpy as np
import pandas as pd
import xarray as xr

data = np.random.rand(4, 3)
times = pd.date_range("2000-01-01", periods=4)
locs = [30, 60, 90]
coords = [("time", times, {"axis": "T"}), ("space", locs)]
foo = xr.DataArray(data, coords, dims=["time", "space"])
ds1 = xr.Dataset({"T": foo})
ds1.cf["T"]
```

This will return the `time` variable even though there's a data variable named `T`.

I see two issues here:
1. There's no way to get the data variable `T` with associated CF variables
2. `cf-xarray` should notify the user that there is a clash.

For 1. I propose we add `ds1.cf.get_variable("T")` or `ds1.cf.get_cf_variable("T")`. This will index in the usual xarray style but parse the `coordinates` attributes etc to attach related variables. 

We could do `ds1.cf.get` but I don't like it being different from `ds1.cf.__getitem__`. Though right now `.get` just forwards to xarray, which is also inconsistent with `__getitem__`.  I'll open a separate issue for this. 

cc @allibco

**Comment by allibco** [comment]
Thanks for adding this. I don't think I have anything to add.

**Comment by dcherian** [comment]
Alternate solution is to convert the `values` in `.cf.data_vars` and `.cf.coords` to our nice "CF DataArrays".

So for this example `ds1.cf.data_vars["T"]` will work as intended
