### ISSUE TITLE
Support renaming functions

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#133]
Necessary for `cmip6-preprocessing`

Just need to add the appropriate kwarg names for `rename_dims`, `rename_vars`, `rename` here: https://github.com/xarray-contrib/cf-xarray/blob/674751b59fc5fe32759eda145b1cb6c917633367/cf_xarray/accessor.py#L372-L395

We get some support for free with the `**kwargs` form but it only uses `_get_axis_coord`. 

cc @jbusecke

**Comment by dcherian** [comment]
@malmans2 can this be closed? Or is there something left to do?

**Comment by malmans2** [comment]
Yes, we're covering all renaming functions after #185
