### ISSUE TITLE
How does cf_xarray detect `vertical` coordinates

### ISSUE THREAD

**Issue by ahuang11** [xarray-contrib/cf-xarray#135]
I have a dataset with a coordinate named `lev`.

```
<xarray.DataArray 'lev' (lev: 2)>
array([ 850., 1000.])
Coordinates:
  * lev      (lev) float64 850.0 1e+03
    crs      int64 0
Attributes:
    long_name:  pressure level
    units:      hPa
```

Do I have to have add more attrs?

**Comment by dcherian** [comment]
https://github.com/xarray-contrib/cf-xarray/blob/674751b59fc5fe32759eda145b1cb6c917633367/cf_xarray/accessor.py#L91

Right now it only looks for `positive`

I think adding `hPa` to `units` would be sensible. That would mean adding `"vertical": ("hPa", )` to https://github.com/xarray-contrib/cf-xarray/blob/674751b59fc5fe32759eda145b1cb6c917633367/cf_xarray/accessor.py#L92-L108

**Comment by aulemahal** [comment]
@dcherian  I believe it also looks for the following `standard_names`!
https://github.com/xarray-contrib/cf-xarray/blob/674751b59fc5fe32759eda145b1cb6c917633367/cf_xarray/accessor.py#L53-L63

**Comment by dcherian** [comment]
ah yes :) missed that.

**Comment by ahuang11** [comment]
Thanks!
