### ISSUE TITLE
Should atmosphere_sigma_coordinate be added to the list of standard_names for parsing vertical?

### ISSUE THREAD

**Issue by ahuang11** [xarray-contrib/cf-xarray#139]
Since one of the examples in http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#parametric-vertical-coordinate has "atmosphere_sigma_coordinate" 

```
Example 4.3. Atmosphere sigma coordinate
float lev(lev) ;
  lev:long_name = "sigma at layer midpoints" ;
  lev:positive = "down" ;
  lev:standard_name = "atmosphere_sigma_coordinate" ;
  lev:formula_terms = "sigma: lev ps: PS ptop: PTOP" ;
  lev:computed_standard_name = "air_pressure" ;
```

**Comment by dcherian** [comment]
Please see #87. It's useful to distinguish between the sigma coordinate (as "axis") and the computed vertical "coordinate"

**Comment by ahuang11** [comment]
Is there an explanation between axis and coordinate? I think axis as the indexing dimension in xarray?

**Comment by dcherian** [comment]
yeah loosely we expect axis to map to "dimension", coordinate to either dimension or non-dimension coordinate. 

In the simplest cartesian case, axis and coordinate are interchangeable.

**Comment by ahuang11** [comment]
So the title of this issue should be "for parsing Z" if I am following because native model output usually is output in sigma model level coordinates.

**Comment by dcherian** [comment]
Alternatively, we could add an extra `"parametric"` special name that matches variables with attributes `formula_terms`, `computed_standard_name`. The problem is that these variables still have `positive` (similarly for the ocean ROMS model) so they'll match for `vertical` too :(

**Comment by dcherian** [comment]
We already match `atmosphere_sigma_coordinate` for `Z`; https://github.com/xarray-contrib/cf-xarray/blob/674751b59fc5fe32759eda145b1cb6c917633367/cf_xarray/accessor.py#L64-L77
