### ISSUE TITLE
Support model initialization time + ensemble member + forecast_tau axes

### ISSUE THREAD

**Issue by ahuang11** [xarray-contrib/cf-xarray#140]
Title

**Comment by ahuang11** [comment]
Also forecast tau

**Comment by dcherian** [comment]
An example use case would help here.

If there is an associated `standard_name`, some stuff should already work. I guess I don't know what you're asking for :) Please add examples.

**Comment by ahuang11** [comment]
To start, I would love if it can label and standardize the coordinates in this dataset (although I know the conventions say IRIDL lol, but forecast datasets with lead and initializations).
```
import xarray as xr
import cf_xarray
ds = xr.open_dataset('http://iridl.ldeo.columbia.edu/SOURCES/.Models/.NMME/.NCEP-CFSv2/.HINDCAST/.MONTHLY/.sst/dods', decode_cf=False)
ds.cf.coordinates
```
![image](https://user-images.githubusercontent.com/15331990/105906976-007b5200-5fea-11eb-95af-385e9b27752d.png)

Once that's done, it'd be nice to have something like verification time alignment where it's able to automatically align a verification dataset with a forecast. https://github.com/mktippett/ENSO/blob/master/ForecastVerification.ipynb
```
cfsv2_ds["o"] = (( "L", "S"), o.sel(T=T))
cfsv2_ds
```

To me, it sounds like it's within the scope of cf_xarray since I think cf_xarray already handles rolling longitudes across the edges if I am not mistaken?

**Comment by ahuang11** [comment]
Maybe the title should state "axes" instead of "coordinates" since these dimensions are usually 1D besides verification time
which consists of (Initialization, Lead), or more generally initialization_time + forecast_lead = verification_target

**Comment by dcherian** [comment]
Can you expand the attributes for the coordinate variables in your screenshot please?

I am sympathetic to this change. We need to come up with nice names and criteria for these dimensions though. On the implementation side, I imagine that we'd only be matching `standard_name`, so it'd be nice to generalize `_get_axis_coord` to do just that.

**Comment by ahuang11** [comment]
![image](https://user-images.githubusercontent.com/15331990/105909079-b3e54600-5fec-11eb-8e72-6e81f351a871.png)

**Comment by dcherian** [comment]
So you want to be able to do `ds.cf.mean("realization")` and `ds.cf.rename(realization="ensemble_member")`?

**Comment by ahuang11** [comment]
Sure plus:
`ds.cf.rename_like` -> `ds.cf.align_like()`

**Comment by dcherian** [comment]
> Sure plus: ds.cf.rename_like -> verf_ds.cf.align_like(fcst_ds) where verf_ds contains target/valid time and fcst_ds contains initialization/tau

This is a little too specialized but we should add support for `dims` other than `x,y,z,t,latitude,longitude,vertical,time`. With support for standard_name you could be doing `o.cf.sel(target_time=fct_ds.cf["initialization_time"])` assuming `target_time` and `initialization_time` are the appropriate standard names.

**Comment by ahuang11** [comment]
Does rolling handle taking the means across the edges of the dataset, or is it simply the equivalent of doing `ds.rolling.mean(lon=5)`? https://cf-xarray.readthedocs.io/en/latest/examples/introduction.html#Rolling-&-coarsen

Maybe I was mistaken.

**Comment by dcherian** [comment]
No it does not. Right now all its doing is rewriting args, kwargs to let you make use of attributes.

**Comment by ahuang11** [comment]
Okay then what I requested in my latter comment is out of scope for now~ but eventually that'd be ideal!
