### ISSUE TITLE
Drop is not working

### ISSUE THREAD

**Issue by malmans2** [xarray-contrib/cf-xarray#143]
Looks like drop is not working... Is it supposed to work or is not implemented?

```python
import cf_xarray
import xarray as xr

airds = xr.tutorial.open_dataset("air_temperature")
airds.air.attrs["standard_name"] = "air_temperature"

# Fails: Drop using standard name
airds.cf.drop("air_temperature")

# Works: Drop using variable name
airds.cf.drop("air")
```
Error is: `ValueError: One or more of the specified variables cannot be found in this dataset`

**Comment by dcherian** [comment]
Needs to be implemented. 

Add `names` (signature of `drop_vars`) and `labels` (signature of `drop`, `drop_sel`) with appropriate mappers here along with a test
https://github.com/xarray-contrib/cf-xarray/blob/674751b59fc5fe32759eda145b1cb6c917633367/cf_xarray/accessor.py#L379
