### ISSUE TITLE
question about time_bnds missing warning

### ISSUE THREAD

**Issue by allibco** [xarray-contrib/cf-xarray#144]
Another question:

I am unclear about why I am getting a warning about missing time_bnds. I don't think that I need it (?)  Here is what happens:

![image](https://user-images.githubusercontent.com/14944423/106065598-c2992f00-60b8-11eb-9d54-eeea2b4c5b26.png)

![image](https://user-images.githubusercontent.com/14944423/106065622-c88f1000-60b8-11eb-8aba-4742b6c27880.png)

It also happens with `cam_ts.cf.data_vars["TS"]`.

If I remove the time dimension, then I don't have a problem:
`t0 = cam_ts.isel(time=0)`
`t0.cf["TS"]`
but in many cases I need the time dimensions...

Let me know if I need to provide more information, and thanks again for the help.

**Comment by malmans2** [comment]
Does `time` have the attribute `bounds="time_bnds"`?
If yes, you could get rid of it as the variable `time_bnds` does not exist.
For example: `cam_ts.attrs.pop("bounds")`

**Comment by malmans2** [comment]
Actully, `cam_ts["time"].attrs.pop("bounds")`

**Comment by dcherian** [comment]
We should disable this warning for `bounds` when extracting a dataset. We can't attach the bounds variable to DataArray anyway.

**Comment by allibco** [comment]
Thanks for your help.  I did `cam_ts["time"].attrs.pop("bounds")` as suggested and that removed the warning.
