### ISSUE TITLE
Separate cf axes for experiment / run?

### ISSUE THREAD

**Issue by ahuang11** [xarray-contrib/cf-xarray#160]
I have two separate model experiments / runs as dimensions and I want to take the difference across them, e.g. `ds.cf.diff('run')` or something similar (similar request as https://github.com/xarray-contrib/cf-xarray/issues/140)

I don't exactly see a standard name for separate experiments / runs in the CF Catalog, but maybe I missed it?

**Comment by dcherian** [comment]
realization?

You can also set a standard name of your choice... We don't validate against the standard name table...

**Comment by ahuang11** [comment]
What if both runs have their own ensemble members

**Comment by dcherian** [comment]
I don't know of a standard name for what you want. I suggest making one up and setting it as `standard_name` on the dimensions. Things should just work then.

**Comment by dcherian** [comment]
maybe @ocefpaf has ideas

**Comment by dcherian** [comment]
@jbusecke might have ideas too

**Comment by jbusecke** [comment]
In CMIP6 speak I think `run=experiment`, but I have no clue about how that relates to cf conventions, def need to read up a bit on that!

**Comment by dcherian** [comment]
Looks like `experiment_id` is used (https://esgdata.gfdl.noaa.gov/search/cmip6-gfdl/) and `member_id` is ensemble member that would be `realization` in CF standard name speak

**Comment by ocefpaf** [comment]
> maybe @ocefpaf has ideas

I wish. I steer away from standard_names!
