### ISSUE TITLE
Regional operations

### ISSUE THREAD

**Issue by ahuang11** [xarray-contrib/cf-xarray#161]
http://cfconventions.org/Data/standardized-region-list/standardized-region-list.html
I wonder if could do something like
`ds.cf.mean(region='contiguous_us')`

although the catalog doesn't really specify bounds :/

**Comment by aulemahal** [comment]
Seems to me a bit complicated for cf-xarray as there more than one way to perform a "spatial mean" :
- simple mean of all grid cells whose center fall within the polygon (as `clisops.core.subset.subset_shape`,  `rioxarray` or `regionmask` do).
- more complex, exact mean when partial overlap are taken into account (as `xesmf.SpatialAverager` does).

But a centralized repo containing all cf regions would be nice.

Ref:
clisops : https://clisops.readthedocs.io/en/latest/api.html#clisops.core.subset.subset_shape
rioxarray : https://gis.stackexchange.com/questions/328128/extracting-data-within-geometry-shape/328320#328320
regionmask : https://regionmask.readthedocs.io/en/stable/
xESMF : https://pangeo-xesmf.readthedocs.io/en/latest/notebooks/Spatial_Averaging.html

**Comment by ahuang11** [comment]
Since cf-xarray is related to CF Conventions, it can contain all the CF regions and do basic simple mean of grid cells? More complex ones can be passed onto other libraries by importing and calling the relevant functions?

**Comment by aulemahal** [comment]
Oh! I was under the impression that all CF regions would be arbitrary polygons, not simple bbox!
If its only a question of a mean in a bbox, xarray already offers most of the algorithm, so might be nice to have that in cf-xarray.

But then I think the mean-over-a-polygon thing should be implemented by xarray. It is not in cf-xarray's scope to implement computational methods I think. Same as `ds.cf.rolling` which is just a cf-standardized bridge to xarray's rolling op.

Anyway, let's see what @dcherian thinks.

**Comment by ahuang11** [comment]
Oops, I don't know either! I thought they were simple bbox regions.

**Comment by ahuang11** [comment]
You might be right that it's complex shapefiles:
http://cfconventions.org/cf-conventions/cf-conventions.html#geographic-regions

**Comment by dcherian** [comment]
I don't know that there is a standardized definition for these regions, so not sure what cf_xarray can contribute here.

`regionmask` already provides a list of "standard" regions  for different standards

**Comment by dcherian** [comment]
Looks like there's no real action to be taken. Please reopen if you have ideas.
