### ISSUE TITLE
[feature request] integration of DeepSource

### ISSUE THREAD

**Issue by withshubh** [xarray-contrib/cf-xarray#170]
Hi :wave: 

I fixed a few code quality issues(PR #167) that were caught by running DeepSource static analysis.

There are a few more performances, bug risk, anti-pattern & security issues that exist in the code. Consider taking a look at the [report generated by DeepSource](https://deepsource.io/gh/withshubh/cf-xarray/). 

I'd suggest you activate the analysis on this repo that will help improve the code quality.

##### Using DeepSource to continuously analyze your repository

- This repo has the configuration file required to configure analysis settings (merged in #167).
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Activate analysis [here](https://deepsource.io/gh/xarray-contrib/cf-xarray/).

**Comment by dcherian** [comment]
thanks some of those suggestions are nice but most are noisy :(. I think we'll pass on this for now.

Thanks for bringing it up
