### ISSUE TITLE
release

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#178]
There are many cool new features so I think we should release 0.5.0

@malmans2 do you want to issue this release?

The steps are
- update whats new with version number & date.
- "draft a new release" on github.
- after that it hsould automatically upload to pypi

**Comment by malmans2** [comment]
Sure! 
The conda-forge bot didn't show up yet, but I guess it takes some time...

**Comment by malmans2** [comment]
All set I think, I can't merge the conda-forge PR though.

**Comment by dcherian** [comment]
Thanks! I'll add you as a maintainer on conda-forge
