### ISSUE TITLE
Accessing with standard name broken on DataArrays.

### ISSUE THREAD

**Issue by aulemahal** [xarray-contrib/cf-xarray#179]
So I know this is a strange call, but it did work before and doesn't anymore with version 0.5.0. I think this has to do with the refactor related to  `_get_all` and friends.

## What I did
```python
import cf_xarray
import xarray as xr

ds = xr.tutorial.open_dataset('air_temperature')
ds.lat.cf['latitude']
```

I expected to receive `ds.lat` back, as was the behaviour before. But now, an error is raised:
```python3
<ipython-input-26-1c2f69690a8b> in <module>
----> 1 ds.lat.cf['latitude']

~/Python/cf-xarray/cf_xarray/accessor.py in __getitem__(self, key)
   1723             )
   1724 
-> 1725         return _getitem(self, key)
   1726 
   1727     pass

~/Python/cf-xarray/cf_xarray/accessor.py in _getitem(accessor, key, skip)
    619         if "coords" not in skip and k in _AXIS_NAMES + _COORD_NAMES:
    620             names = _get_all(obj, k)
--> 621             check_results(names, k)
    622             successful[k] = bool(names)
    623             coords.extend(names)

~/Python/cf-xarray/cf_xarray/accessor.py in check_results(names, k)
    607     def check_results(names, k):
    608         if scalar_key and len(names) > 1:
--> 609             raise KeyError(
    610                 f"Receive multiple variables for key {k!r}: {names}. "
    611                 f"Expected only one. Please pass a list [{k!r}] "

KeyError: "Receive multiple variables for key 'latitude': ['<this-array>', 'lat']. Expected only one. Please pass a list ['latitude'] instead to get all variables matching 'latitude'."
```

The error seems to be related to `get_with_standard_name` which will return `<this-array>` in our case.  

EDIT: Then example below fails because of the bug I highlighted, but it realized it should fail nonetheless.

<details>

Another failing example:
```python3
ds.air.attrs['standard_name'] = 'stdname'

ds.cf['stdname']  #-> works and returns ds.air
ds.air.cf['stdname']
```
The last line fails with
```
KeyError: "DataArray.cf does not understand the key 'stdname'. Use 'repr(DataArray.cf)' (or 'DataArray.cf' in a Jupyter environment) to see a list of key names that can be interpreted."
```

I think `_get_with_standard_name` must be modified to not return '<this-array>', but the var name instead.

</details>

**Comment by malmans2** [comment]
I think one issue is that this xarray private method is doing something undesirable:
https://github.com/xarray-contrib/cf-xarray/blob/af85a2a43d53032c0c95d1f4acd1c536abcbbbf4/cf_xarray/accessor.py#L354

For example:
```python
import xarray as xr
ds = xr.tutorial.open_dataset('air_temperature')
ds.lat._to_temp_dataset()
```
```
<xarray.Dataset>
Dimensions:       (lat: 25)
Coordinates:
  * lat           (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 22.5 20.0 17.5 15.0
Data variables:
    <this-array>  (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 22.5 20.0 17.5 15.0
```

**Comment by aulemahal** [comment]
I'm not sure how that would be undesirable?
I think is right in allowing this kind of access: `ds.lat.lat.lat.lat.lat` , i.e. coordinates are coordinates of themselves.

Also I removed the second example from my initial issue, because as `ds.air.air` fails, so should `ds.air.cf['stdname']`. 

I will push a fix in a minute.

**Comment by dcherian** [comment]
released with fix.

**Comment by aulemahal** [comment]
Thanks!
