### ISSUE TITLE
Documentation notebook is broken

### ISSUE THREAD

**Issue by malmans2** [xarray-contrib/cf-xarray#182]
Looks like there are two issues:

1. For some reason, the latest rtd build does not show any output after the first error (cell 11, the exception tag looks OK)
2. Cell 23 is broken: `pop.cf["TEMP"].cf.rename_like(ds)`, and I think we didn't catch it in previous PRs because of point 1.

`pop.cf["TEMP"].cf.rename_like(ds)` fails because we are trying to rename:
```
Coordinates:
- CF Axes: * X: ['nlon']
           * Y: ['nlat']
             Z, T: n/a

- CF Coordinates:   longitude: ['TLONG']
                    latitude: ['TLAT']
                    vertical, time: n/a

- Cell Measures:   area, volume: n/a

- Standard Names:   n/a
```
to
```
Coordinates:
- CF Axes: * X: ['lon']
           * Y: ['lat']
           * T: ['time']
             Z: n/a

- CF Coordinates: * longitude: ['lon']
                  * latitude: ['lat']
                  * time: ['time']
                    vertical: n/a

- Cell Measures:   area, volume: n/a

- Standard Names: * latitude: ['lat']
                  * longitude: ['lon']
                  * time: ['time']

Data Variables:
- Cell Measures:   area, volume: n/a

- Standard Names:   air_temperature: ['air']
```
We get an error because we need to rename both `nlon` and `TLONG` to `lon`.
Maybe @dcherian already took care of this in #165?

**Comment by dcherian** [comment]
Don't think so, we should raise a warning in this case I think, and skip renaming.
