### ISSUE TITLE
earthcube abstract

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#186]
I think we should put together a notebook demonstrating cf-xarray and its uses in xesmf, xroms etc.

https://www.earthcube.org/2021-earthcube-annual-meeting

Abstracts due April 15

## Call For Notebooks 

As scientific studies become more data intensive and software dependent, reproducibility principles and other factors increase the importance of making work such as **reusable workflows**, software, and data-access procedures citable.
...

Submitted notebooks should highlight a tool (i.e. software, service, library, dataset, standard), explaining and demonstrating interactively how the tool may be used to address a significant problem in geoscience.  There will be two tracks. One track will be focused on submissions where the goal is describing scientific outputs. In this case, the novelty is based on the analysis being done and the scientific conclusions drawn. **The other is on demonstrating new software and tools. Here the emphasis is on new software and showing how it can be used.**

Submissions will be peer reviewed in terms of their impact on geoscience research and overall usability, by reviewers from the geoscience and cyberinfrastructure communities.  Authors of accepted notebooks will have the opportunity to present their notebook at the EarthCube Annual Meeting and their notebooks will be published in an EarthCube digital proceedings for others to discover, use, and cite.

    Notebook abstracts are due April 15.

    Final notebooks are due on May 15.

## Guidelines: 

1) Submissions should provide a Jupyter notebook and use an EarthCube TAC template in Python 3 (an example can be viewed here, see the long version of the template for more details regarding the guidelines; please note that the final version of the template will be provided in early April.)

2) Authors should share their notebook in a self-contained runnable environment (e.g., use of Binder or Docker is strongly recommended), so that reviewers and the community can run the notebook without having to install required libraries locally. 

3) Submissions should take the form of an abstract (due April 15, 2021) and URL (due May 15, 2021)  to a repository containing the notebook.

**Comment by dcherian** [comment]
At the very least it'll make a cool demo notebook for the docs.

Anyone who has committed to the repo is welcome to be a co-author. Please comment here if you would like to be listed as co-author.

**Comment by malmans2** [comment]
Good idea! I'd be happy to help with abstract/notebook.

**Comment by aulemahal** [comment]
Cool! I'd also be happy to help with this. I have a regridding notebook with an example explicitly using cf-xarray that I can adapt.

**Comment by aulemahal** [comment]
As there been work done on this? I have time tomorrow to start a notebook and at least a basic example playing with bounds, taken from regridding stuff I have.

**Comment by dcherian** [comment]
yes! I'd like to emphasize working with multiple datasets in a consistent manner. Regridding could totally be part of that workflow.

**Comment by dcherian** [comment]
Took a start here: https://docs.google.com/document/d/1I4hr-SLWP5_x1jDkJTtRIhqSndkKuklAQ0BwZ9TYEEo/edit?usp=sharing

Please add your name along with edits.

**Comment by dcherian** [comment]
Hi all

I am unfortunately just too busy to spend time on this. If someone wants to take the lead instead, please volunteer. I can contact the organizers to change the author order appropriately. 

If everyone is busy, I think we can just withdraw the abstract.

**Comment by malmans2** [comment]
I'm happy to work on the notebook end extend #194 (deadline is on May 15, right?).
If you can present the notebook at the meeting, I think it makes sense having you as first author! (not sure if I'd be able to attend)

I personally don't use datasets on the cloud, so I'd need a few tips to get started, such as datasets to use and how to access them.

**Comment by dcherian** [comment]
Thanks Mattia!

> If you can present the notebook at the meeting, I think it makes sense having you as first author! (not sure if I'd be able to attend)

OK. If it ends up being too much, it's OK to drop it.

> I personally don't use datasets on the cloud, so I'd need a few tips to get started, such as datasets to use and how to access them.

I don't either but when i do, I copy from http://gallery.pangeo.io/

**Comment by malmans2** [comment]
I made some progress with the notebook:
[![Binder](https://binder.pangeo.io/badge_logo.svg)](https://binder.pangeo.io/v2/gh/malmans2/cf-xarray-earthcube/main?filepath=DC_01_cf-xarray.ipynb)

The demo part should be mostly done, just need to fill in section 1 (I guess mainly copy and paste from the abstract) - I won't have much time to spend on it tomorrow.
I'll leave it up to you if you want to go ahead and submit or prefer withdrawing the abstract (I'm pretty sure the actual meeting time is not good for Europe, so unlikely I'll be able to attend).

Let me know if you want me to transfer the repo!

**Comment by dcherian** [comment]
Thanks @malmans2 Taking a look now. Can you add @aulemahal and I as "maintainers" on your repo. I think we just go with that for now. Eventually I'd like to add this to the docs and we can figure out how to move the notebook here then.

**Comment by aulemahal** [comment]
Thanks! I'll make some slight changes and push them to the repo.
I can also fill in the header if @dcherian  doesn't have time.
However, I can't present it at the meeting : I am already presenting another one, about our work at xclim and finch.

**Comment by dcherian** [comment]
Great. I'm working through it now and making edits. I'll be done in 20 minutes or so. @aulemahal maybe you can take a look then to avoid conflicts.

**Comment by aulemahal** [comment]
Good. FYI, I fixed the postBuild script (at least on my side the downloads where not all successful).
Changed the two last lines with:
```bash
curl -o data/air_temperature.nc https://raw.githubusercontent.com/pydata/xarray-data/master/air_temperature.nc
curl -o data/sic_SImon_CCCma-CanESM5_ssp245_r13i1p2f1_2020.nc https://raw.githubusercontent.com/Ouranosinc/xclim-testdata/main/cmip6/sic_SImon_CCCma-CanESM5_ssp245_r13i1p2f1_2020.nc
```

**Comment by dcherian** [comment]
Alright I pushed my changes to the repo. The downloads worked for me somehow.

Let me know when you're done. I can work on the text some more.

**Comment by aulemahal** [comment]
@dcherian  I made my minor changes! 

So I made the postBuild changes. I think the issues comes from different version/flavors of `curl`. Now all URLs are direct links, so nobody should have problems.

I also changed the source dataset for `ds_cmip6_oce`. The one that was used was _huge_. On my laptop, the temp anomaly example was exploding the RAM. AFAIK, binder is limiter to 2 GB, so it would have failed there too! I found a coarser resolution dataset that looks pretty much the same, and it runs well. I think it peaks at 1.5 GB now. 
I did try to control it via an explicit dask client, but the only time it worked, the computation would have taken over 30 mn...

**Comment by dcherian** [comment]
Thanks all! I've jsut submitted the link: https://binder.pangeo.io/v2/gh/malmans2/cf-xarray-earthcube/main?filepath=DC_01_cf-xarray.ipynb . It looks awesome!

I changed the author order to Almansi, Cherian, Bourgault. I thought it reflected the effort that went in to the final notebook. I can present it. I'll email the organizers to see if I can get the author order changed in the program.

**Comment by malmans2** [comment]
Thanks Deepak!

**Comment by dcherian** [comment]
Nice work everyone. Looks like we got great reviews... I'll start addressing them soon.

---

**Reviewer comments:** Please include refernces. Missing list of references in the end of the notebook including software and DOIs when available: CF-Conventions, Xarray, MOM6, CORE, ... and the cf-xarray package. Suggestions: (a) Documentation of function assign_coordinates_and_cell_measures(), add an example section so the reader can quickly figure out what it does; (b) assign_coordinates_and_cell_measures(), I believe that set() does not guarantee order. Could that be a bug?; (b) Probably useful to add some information as attributes for the guesses, such as guess_coord_axis() or when guessing the bounds of spatial coordinates on section 5.2.2. Maybe add an attribute "note" or "history" for lon_bounds & lat_bounds, informing that it was a guess. This information might help to debug long data pipelines. I tend to use a warning with logging; (c) warning message (...xesmf/frontend.py:478: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version. keep_attrs=keep_attrs,); (d) Use Zenodo to assign DOIs for the package (cf-xarray) releases. If you do so, you might find this useful (https://github.com/castelao/inception), and add a ".zenodo.json" and a CITATION.cff;

**Reviewer comments:** This is a truly masterful presentation of the material: crystal-clear prose interleaved with immaculately formatted code. It so happens that this material is quite relevant to my current work, and I found myself enthusiastically copy-and-pasting sections from this notebook into my own notebooks as a read through it.

It's difficult to make a subject such as arcane metadata standards accessible and engaging reading, but that goal was achieved in spades here. If I had to select only one notebook to recommend for publication, it would be this one.

Outstanding.

---
