### ISSUE TITLE
lat/lon_bnds with units attribute identified as latitude/longitude coordinate variables when registered as coords of the Dataset

### ISSUE THREAD

**Issue by sol1105** [xarray-contrib/cf-xarray#191]
Hello,

I encountered a minor problem when trying to identify the latitude/longitude coordinate variables of an xarray.Dataset. I used version 0.5.1 of cf_xarray.

#### Description
When the latitude bounds and longitude bounds are registered as coordinates of the xarray.Dataset and they have a units attribute ("degrees_north/east") cf_xarray identifies them as latitude / longitude coordinate variables, which I did not expect.

The latitude bounds and longitude bounds get registered as coordinates of the xarray.Dataset for example when calling `xarray.open_dataset(path_to_ds, decode_coords="all")` .

I'm not sure, but I think CF conventions allow for lat_bnds/lon_bnds to have a units attribute. At least I know that such CMIP6 datasets passed a quality control including a CF-checker.

#### Short example

```python
import xarray as xr
import cf_xarray as cfxr
import numpy as np

lons=np.zeros((10))
lats=np.zeros((10))
lat_bounds=np.zeros((10,2))
lon_bounds=np.zeros((10,2))

ds = xr.Dataset(data_vars={},
                coords={'lat': ('lat', lats),
                        'lon': ('lon', lons),                      
                        'lat_bnds': (['lat', 'bnds'], lat_bounds),
                        'lon_bnds': (['lon', 'bnds'], lon_bounds)})


ds["lat"].attrs = {
    "bounds": "lat_bnds",
    "units": "degrees_north",
    "long_name": "latitude",
    "standard_name": "latitude",
    "axis": "Y",
}
ds["lon"].attrs = {
    "bounds": "lon_bnds",
    "units": "degrees_east",
    "long_name": "longitude",
    "standard_name": "longitude",
    "axis": "X",
}
ds["lat_bnds"].attrs = {
    "long_name": "latitude_bounds",
    "units": "degrees_north",
}
ds["lon_bnds"].attrs = {
    "long_name": "longitude_bounds",
    "units": "degrees_east",
}

print(ds.cf["latitude"].name)
```

That results in the following error as it also identifies lat_bnds for the key "latitude".

```python
KeyError: "Receive multiple variables for key 'latitude': ['lat_bnds', 'lat']. Expected only one. Please pass a list ['latitude'] instead to get all variables matching 'latitude'."
```

Is it the desired behaviour to list all coordinate variables associated with the latitude coordinate (incl. bounds), and not only the latitude coordinate variable itself?

As a workaround for my problem I can use for example `cf_xarray.accessor._get_with_standard_name` or `xarray.reset_coords()`.

**Comment by dcherian** [comment]
Thanks for raising this issue @sol1105 (also excited to see other people using this package, yay!)

You are correct, this seems fairly useless. We should exclude variables named in the `bounds` attribute from such things. For a single `DataArray`, a solution would be to set the `"coordinates"` attribute in either `.attrs` or `.encoding`. For a `Dataset`, we will have to exclude the bounds variables.

**Comment by sol1105** [comment]
Hi @dcherian , 

the fix for this issue works nicely for my application, thank you. I noticed however, that there is one situation when it does not work:
when calling `xarray.open_dataset(path_to_ds, decode_coords="all")`, the CF-attributes like `bounds` get moved from `.attrs` to `.encoding`. The bounds entry in `.encoding` seems to be ignored by cf-xarray, which then identifies again, eg. `lat` and `lat_bnds` as `latitude` coordinate variable.

```python
ds.cf['latitude']
> KeyError: "Receive multiple variables for key 'latitude': ['lat_bnds', 'lat']. Expected only one. Please pass a list ['latitude'] instead to get all variables matching 'latitude'."
```
```python
ds.cf.bounds
> { }
```
Should cf-xarray also make use of the information stored in `.encoding`, or is this rather a problem of `xarray`?

In cf-xarray it could maybe look like this (to allow the bounds to still be registered, when in `.encoding`):

`accessor._getitem.drop_bounds`
```python
@@ -628,7 +630,7 @@ def _getitem(
         # with a scalar key. Hopefully these will soon get decoded to IntervalIndex
         # and we can move on...
         if scalar_key:
-            bounds = {obj[k].attrs.get("bounds", None) for k in names}
+            bounds = {obj[k].attrs.get("bounds", obj[k].encoding.get("bounds", None)) for k in names}
             names = set(names) - bounds
         return names
```

`accessor._get_bounds`
```python
@@ -341,6 +341,8 @@ def _get_bounds(obj: Union[DataArray, Dataset], key: str) -> List[str]:
     for var in apply_mapper(_get_all, obj, key, error=False, default=[key]):
         if "bounds" in obj[var].attrs:
             results |= {obj[var].attrs["bounds"]}
+        elif "bounds" in obj[var].encoding:
+            results |= {obj[var].encoding["bounds"]}
 
     return list(results)
```

**Comment by dcherian** [comment]
That's a bug. PR is welcome!
