### ISSUE TITLE
cf_xarray.__version__ not available

### ISSUE THREAD

**Issue by jbusecke** [xarray-contrib/cf-xarray#207]
Hi, I just tried to track the version of `cf_xarray` that is available on the pangeo google cloud, but I am getting this error.

```python
import cf_xarray
cf_xarray.__version__
```

```
AttributeError: module 'cf_xarray' has no attribute '__version__'
```

`conda list cf_xarray` gives

```
# packages in environment at /srv/conda/envs/notebook:
#
# Name                    Version                   Build  Channel
cf_xarray                 0.5.1              pyh44b312d_0    conda-forge
```

Seems like the version is not packaged properly? Or am I missing something?

**Comment by dcherian** [comment]
oops I think we want to migrate to `pyproject.toml` also
