### ISSUE TITLE
Axes/coordinates info are lost when using `cf.groupby`

### ISSUE THREAD

**Issue by malmans2** [xarray-contrib/cf-xarray#219]
When using `cf.groupby` we loose some CF info.
For example, here we loose the `T` axis and `time` coordinate, which would be `hour`.
Is it possible to return a better object, maybe using the guessing functions?

```python
from cf_xarray.datasets import airds
airds.cf.groupby("T.hour").mean().cf
```
```
Coordinates:
- CF Axes: * X: ['lon']
           * Y: ['lat']
             Z, T: n/a

- CF Coordinates: * longitude: ['lon']
                  * latitude: ['lat']
                    vertical, time: n/a
```

**Comment by dcherian** [comment]
Right because xarray creates a new `hour` coordinate with no attributes. `guess_coord_axis()` will detect it and set attributes.
