### ISSUE TITLE
Support alternative naming conventions

### ISSUE THREAD

**Issue by kthyng** [xarray-contrib/cf-xarray#230]
I am dealing with a variety of DataFrames and Datasets and want to be able to just grab the sea surface height variable, for example, without knowing the standard or variable name. It reminds me of being able to say `ds.cf['X']` without having to type the actual x grid name. In the data and model sets I am using, standard_names are not standard at all, so I have code to search for the variables I want using regular expressions to look for terms in units and `standard_name` and other attributes so that I can then refer to that variable without knowing its variable name. I had to do something similar for `xcmocean` to search through regex patterns for variable matching, which was inspired by some code in `cf-xarray`: https://github.com/pangeo-data/xcmocean/blob/main/xcmocean/accessor.py#L65

If it was in cf-xarray, one could do something like
```
ds.cf['ssh']
```
to get the sea surface height. There also could be more than one sea surface height. One common example would be working with temperature, in which case it would be typical to have both air temp and water temp so that would need to be dealt with. 

An argument against this is that it is sort of like recreating `standard_names` but with my own names and fewer options, which sounds silly. But, I am finding this problem crops up regularly in my work. I suspect this doesn't fit into `cf-xarray`, but it feels in the spirit of the package so I wanted to bring it up. If anyone knows of a better solution to this, I'd be happy to hear about that too! My current plan is to have a very small package to do this, and try to make it both an accessor for both DataFrames and Datasets, though then I might have problems interacting with other accessors.

**Comment by dcherian** [comment]
1. You could use your existing regexey code to add the `standard_name` attribute and the use `.cf[]` for everything else.
2. I would explore using `.cf.rename` to rename to a consistent naming convention.

Can you provide some examples of 'different but similar' names for 3-4 variables? In some way you are really generalizing `.cf.guess_coord_axis` but for a possible `.cf.guess_standard_names` (#201 is related)

**Comment by kthyng** [comment]
> 1. You could use your existing regexey code to add the standard_name attribute and the use .cf[] for everything else.

Sometimes there is already a `standard_name` attribute, but it is different for different models. Would you suggest just overwriting it with a consistent name? 

I see, so I would still need some code, but it would be to pre-process the datasets for use with `cf-xarray`.

> 2. I would explore using .cf.rename to rename to a consistent naming convention.

Do you mean like apply `cf.rename_like` to apply the same `standard_name` to different variables (to apply your first suggestion)? Or instead of overwriting `standard_name`s, just guessing them (as per your next suggestion)?

> for a possible .cf.guess_standard_names

Yes, it is kind of like this. I hadn't thought of overwriting `standard_name`s but now that you have suggested it, yes.

> Can you provide some examples of 'different but similar' names for 3-4 variables?

* ssh: "sea_surface_elevation", "sea_surface_height_amplitude_due_to_geocentric_ocean_tide_geoid_mllw", "sea_surface_height_above_sea_level_geoid_mllw"
* temp: "sea_water_temperature", "sea_water_potential_temperature"
* velocity: "eastward_sea_water_velocity", "sea_water_x_velocity", "water_u" (variable name). But there are a number of variables/standard_names that may include "speed" and "direction" for both air and water-based variables.

Have you thought about a `cf-pandas` package? I will need to do the same things with data in DataFrames.

**Comment by kthyng** [comment]
For this to be useful, there would have to be an established set of variables `standard_name`s that `cf-xarray` uses so that the user can refer to them with for example

```
.cf['sea_surface_elevation']
```

Here is a stab at the list, with the goal of the variables being descriptive but not too specific to a specific vertical datum for example:

* sea_surface_elevation
* sea_water_temperature
* sea_water_salinity
* eastward_sea_water_velocity, northward_sea_water_velocity
* sea_water_speed
* sea_water_to_direction OR sea_water_from_direction
* wind_speed
* wind_speed_of_gust (both wind_speeds tend to be available together, so how to deal with that?)
* sea_ice_speed
* some other sea_ice stuff

**Comment by dcherian** [comment]
Yeah I am suggesting rewrite to something consistent but it's not nice to overwrite `standard_name` if it already exists.

How about if you set `long_name` to your favourite consistent naming convention? We could have `.cf[]` search through both `long_name` and `standard_name` attributes?

> ssh: "sea_surface_elevation", "sea_surface_height_amplitude_due_to_geocentric_ocean_tide_geoid_mllw", "sea_surface_height_above_sea_level_geoid_mllw"

ermagerds.

> "sea_water_temperature", "sea_water_potential_temperature"

These are different! First one is in-situ temperature!

> Here is a stab at the list,

This list is going to be really quite long!

> Have you thought about a cf-pandas package? 

=) no, I really don't use pandas much at all. Convert to xarray no? :P

**Comment by malmans2** [comment]
Slightly related, we don't parse at all the [CF convention table](https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html), but maybe we could extract additional info from there?
For example, there are some aliases mentioned in the descriptions, although there aren't that many. We could also populate missing units...

Also, I'm wondering if parsing the table and use something like [`difflib.get_close_matches`](https://docs.python.org/3/library/difflib.html#difflib.get_close_matches) could be a guessing option for standard names... (Never used it, might be a crazy thing to do with that many standard names, no idea...)

**Comment by dcherian** [comment]
One idea I've been kicking around is the idea of "synonyms" for things like the CMIP6 vocabulary.

So there `thetao` ≡ `sea_water_potential_temperature`; `so` ≡ `sea_water_salinity` etc.

And so if `ds["TEMP"].attrs['standard_name'] = 'sea_water_potential_temperature'` then `ds.cmip["thetao"]` should return `ds["TEMP"]`.

In this case, you could define your custom vocab and use `ds.thyng["sea_surface_elevation"]`.

**Comment by kthyng** [comment]
`cf.guess_standard_name` seems like the way to go. I am copying your `guess_coord_axis` to start it. Are you willing to have a list of variables like I am suggesting? It could indeed be very long. 

@malmans2 I could see that being useful for our selected standard_names, so a subset, to get the units like you said. Esp since there is unit work in here now too.

**Comment by kthyng** [comment]
> the idea of "synonyms"

I like that idea for being able to customize ultimately. But to start we'd still need something canonical to go off of, like our specific list of standard_names, right?

**Comment by dcherian** [comment]
> cf.guess_standard_name seems like the way to go.

Actually I am not so sure any more. What about the following

> But to start we'd still need something canonical to go off of, like our specific list of standard_names, right?

I don't think so. The "canonical" names could be defined as the keys of a "criteria dictionary" like this.

``` python
criteria = {
    "sea_surface_elevation": {"standard_name": ("sea_surface_height*",), "units": ...}
}
```

Annoyingly this "inverts" the criteria dictionary in `criteria.py` but is more readable by sticking all the criteria for a particular variable in one place. If we switched `coordinate_criteria` to use this format, we could potentially reuse the parsing code. It may even speed things up since it's a single dictionary lookup. We may have to just interpret the strings (in `criteria["sea_surface_elevation"]["standard_name"]` as regexes always.

Following @malmans2 point, I think this would allow providing known aliases (annoying to list all combinations though)

``` python
vocab = {
"sea_surface_height": {
    "standard_name": ("sea_surface_height_above_mean_sea_level", "sea_surface_height_above_sea_level")
  },
"sea_surface_height_above_mean_sea_level": {
    "standard_name": ("sea_surface_height",  "sea_surface_height_above_sea_level")
  },
...
}
```

We could generate the CF alias list by parsing the standard name table. We can allow users to plug in their own criteria somehow and allow for a list of such criteria

``` python
cfxr.set_options(
    criteria=(my_custom_criteria, cfxr.criteria.cf, cfxr.criteria.cmip6)
)
```

@kthyng Would this format allow you to specify all the criteria you use now?

---
`get_close_matches` looks cool but could it fail spectacularly for things like `sea_surface_*` :) Maybe we just run it with a high possibility score? From the docstring:

```
>>> get_close_matches('accept', keyword.kwlist)
['except']
```

**Comment by kthyng** [comment]
I can't quite see through what you are describing. But it sounds similar to the idea before. Are you saying to define a dictionary of keys of a specific standard name for a variable with ways to recognize that variable in its own dictionary? I am not sure how to get it started but I would like to work on it.

**Comment by dcherian** [comment]
> Are you saying to define a dictionary of keys of a specific standard name for a variable with ways to recognize that variable in its own dictionary?

The keys can be any name you want... `ssh` in your case for e.g., and yes the values are criteria for recognizing that variable.

I think a good way to proceed would be to modify the `coordinate_criteria` dictionary here to this new format
https://github.com/xarray-contrib/cf-xarray/blob/820ca440392cd3ca5b9074d3983875435eaecce2/cf_xarray/criteria.py#L12-L17

so something like

```
coordinate_criteria = {
    "latitude": {
        "standard_name": ("latitude",), 
		"units: (
            "degree_north",
            "degree_N",
            "degreeN",
            "degrees_north",
            "degrees_N",
            "degreesN",
        )
	},
	...
}
```

and then fix `_get_axis_coord` to deal with the changes.
https://github.com/xarray-contrib/cf-xarray/blob/820ca440392cd3ca5b9074d3983875435eaecce2/cf_xarray/accessor.py#L221-L232

We can then generalize the code in `_get_axis_coord` to deal with custom dictionaries.

**Comment by kthyng** [comment]
Ok I'll give it a go and get back to you.

**Comment by kthyng** [comment]
Ok I made changes in a branch [here](https://github.com/kthyng/cf-xarray/tree/variable_naming). @dcherian can you take a look? I was able to match some behavior from without and with the changes in a test dataset of my own, but the tests didn't all run so it is not correct yet.

**Comment by dcherian** [comment]
From a quick look that looks right. Can you open a PR please?

**Comment by kthyng** [comment]
PR #233

**Comment by dcherian** [comment]
I merged #233. I think a good next step would be getting 

```
cfxr.set_options(
    criteria=(my_custom_criteria, cfxr.criteria.cf, cfxr.criteria.cmip6)
)
```

to work with `my_custom_criteria` be a dictionary like `coordinate_criteria` but with your criteria for `ssh`.

I would try creating a new mapper `_get_custom_criteria` that generalized `_get_axis_coord`.

**Comment by kthyng** [comment]
> ```
> cfxr.set_options(
>     criteria=(my_custom_criteria, cfxr.criteria.cf, cfxr.criteria.cmip6)
> )
> ```

Where do you imagine this going?

> I would try creating a new mapper `_get_custom_criteria` that generalizes `_get_axis_coord`.

would `_get_custom_criteria` replace `_get_axis_coord` or be another function in addition to it?

**Comment by dcherian** [comment]
> cfxr.set_options(criteria=(my_custom_criteria, cfxr.criteria.cf, cfxr.criteria.cmip6))

I see this as the public API allowing users to plug in their own vocabulary. We can provide the "CF standard name aliases" and maybe CMIP6 vocabularies.

> would _get_custom_criteria replace _get_axis_coord or be another function in addition to it?

Yes I imagine replacing it as `_get_axis_coord(**kwargs) ≡ _get_custom_criteria(criteria=coordinate_criteria, **kwargs)`

and 
``` python
def _get_custom_criteria(criteria=None, key, ...):
	if criteria is None:
		criteria = OPTIONS["criteria"]  # set by set_options

	# copy over from _get_axis_coord
```

Then if you plug in `_get_custom_criteria` here:
https://github.com/xarray-contrib/cf-xarray/blob/a8986412a542aa7d52956a546707e54224796759/cf_xarray/accessor.py#L315
hopefully everything will *just* work at least for your initial use case of mapping a list of standard_names to a custom name like `ssh`. 

How does this sound to you?

**Comment by kthyng** [comment]
I can't see through it all yet but I'll go through these steps and see what I can do. 

Let me summarize and see if this sounds right. `my_custom_criteria` is a mapping from names I want to use to standard_names, then `cfxr.criteria.cf` is the built-in mapping from those standard names to patterns to match to identify variables as those names. What is `cfxr.criteria.cmip6` then? I thought it was another customized mapping.

**Comment by kthyng** [comment]
I have initial changes here, but nothing works yet. I am hoping this is a starting place from which we can iterate. https://github.com/kthyng/cf-xarray/tree/variable_naming

**Comment by dcherian** [comment]
can you open a PR? I'll push a commit then that implements `set_options`

**Comment by kthyng** [comment]
I apparently forgot to update my branch after the last PR and now when I try to update it with the changes from upstream, it says it is going to update my kthyng branch (good) but then eventually after I choose a conflict resolution, it says it will update "main" which I think is in the upstream so I am not sure how to get the upstream changes without messing it up! And all that so that I can then make a PR. I'll try again in a bit.
