### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kthyng** [xarray-contrib/cf-xarray#241]
@dcherian Do you have a method to when you do releases? I am looking to have some packages depend on the new custom criteria/vocab changes but I need them on conda-forge for access. What timeline might I expect for that? Thanks!

**Comment by dcherian** [comment]
No method. I'd like to fix #237 if possible. Do you have the time to take a look at that?

**Comment by kthyng** [comment]
I'll go look at that and close here.
