### ISSUE TITLE
Remove nonexistent variable names from properties like bounds, cell_measures, formula_terms

### ISSUE THREAD

**Issue by tomvothecoder** [xarray-contrib/cf-xarray#254]
I am using `cf-xarray` to write a custom accessor related to coordinate bounds.

The Problem:
* I found that if you drop existing bounds vars, the key-value pair for is still retained in `ds.cf.bounds` dict. This test was performed on a real-world `.nc` file.

Expected Behavior:
* The corresponding key-value pair for a dropped bound var should be dropped from the `ds.cf.bounds` dict.

Steps to Reproduce:
```
import cf_xarray as cfxr
import xarray as xr

$ ds = xr.open_dataset(...)
$ ds.data_vars
Data variables:
    time_bnds  (time, bnds) datetime64[ns] 1850-01-01 1850-02-01 ... 2006-01-01
    lat_bnds   (lat, bnds) float64 -90.0 -89.38 -89.38 ... 89.38 89.38 90.0
    lon_bnds   (lon, bnds) float64 -0.9375 0.9375 0.9375 ... 357.2 357.2 359.1
    ts         (time, lat, lon) float32 252.7 252.7 252.7 ... 248.2 248.2 248.2

$ ds.cf.bounds
{'longitude': ['lon_bnds'],
 'X': ['lon_bnds'],
 'Y': ['lat_bnds'],
 'latitude': ['lat_bnds'],
 'lon': ['lon_bnds'],
 'lat': ['lat_bnds'],
 'time': ['time_bnds'],
 'T': ['time_bnds']}

$ ds = ds.drop_vars("lon_bnds")
$ ds.data_vars
Data variables:
    time_bnds  (time, bnds) datetime64[ns] 1850-01-01 1850-02-01 ... 2006-01-01
    lat_bnds   (lat, bnds) float64 -90.0 -89.38 -89.38 ... 89.38 89.38 90.0
    ts         (time, lat, lon) float32 252.7 252.7 252.7 ... 248.2 248.2 248.2

# "longitude" : ["lon_bnds"] should be dropped from the dict
$ ds.cf.bounds
{'longitude': ['lon_bnds'],
 'X': ['lon_bnds'],
 'Y': ['lat_bnds'],
 'latitude': ['lat_bnds'],
 'lon': ['lon_bnds'],
 'lat': ['lat_bnds'],
 'time': ['time_bnds'],
 'T': ['time_bnds']}

```

https://github.com/xarray-contrib/cf-xarray/blob/16d8c399048ba168d65eaabe1d3402922b1145c7/cf_xarray/accessor.py#L1865-L1883

Alternatives I've Considered:
* I loop through a statically defined list of coordinates and use `ds.cf.bounds.get_bounds()` instead.
```
    missing_bounds = []
    for coord in coords:
        try:
            dataset.cf.get_bounds(coord)
        except KeyError:
            missing_bounds.append(coord)
```

**Comment by dcherian** [comment]
Thanks @tomvothecoder . I'm excited to see you using this package!

What's happening is that you still have the `bounds` attribute specified on the `longitude` variable (which points to `lon_bounds`) and we do not currently check whether that variable is present in the dataset.

This is also true for the `cell_measures` attribute.

Though interestingly we drop nonexistent variable names in the repr.

I think we should indeed drop nonexistent variable names, so that we are a bit more resilient to out-of-date metadata.

cc @malmans2

**Comment by tomvothecoder** [comment]
Thanks for the quick update @dcherian! This package is awesome and I appreciate everyone's work.

I'll open up a PR with a potential fix when I have the capacity to and if no one hops on it first.

**Comment by huard** [comment]
I stumbled on the same issue.

**Comment by dcherian** [comment]
Can you try the main branch please? The latest commit might fix this issue, but I haven't had time to check. If it does, I can issue a new release

**Comment by huard** [comment]
Hum, tried with 0.6.2.dev4+g31ceff2 and it doesn't look like it did.

I just started from a Dataset with bounds then dropped them. `describe` tells me there are no bounds, as expected, but `bounds` still refer to now non-existent bounds.

**Comment by huard** [comment]
Another way to trigger this is to start from a dataset with bounds, select a variable, then create a dataset from it. 
```python
>>> vds = ds.tas.to_dataset(name="tas")
>>> vds.cf.bounds
{'lon': ['lon_bnds'],
 'longitude': ['lon_bnds'],
 'latitude': ['lat_bnds'],
 'time': ['time_bnds'],
 'lat': ['lat_bnds'],
 'X': ['lon_bnds'],
 'T': ['time_bnds'],
 'Y': ['lat_bnds']}
```
but `vds.cf.get_bounds("latitude")` will fail.
