### ISSUE TITLE
Warning: Variables not found in object but are referred to in the CF attributes

### ISSUE THREAD

**Issue by kthyng** [xarray-contrib/cf-xarray#263]
Do you know how to avoid this warning? 

![image](https://user-images.githubusercontent.com/3487237/135932822-1b2b2ae2-c954-466f-9799-56b5c5a6a3e4.png)

It is overwhelming some work I'm doing. 

Thanks!

**Comment by dcherian** [comment]
1. There is some attribute referring to those variables, so you  could delete that.
2. Use warnings.simplefilter https://docs.python.org/3/library/warnings.html
3. We could add an option to disable this warning (warning is on by default).

**Comment by kthyng** [comment]
@dcherian Ah, ok I was able to figure out the issue with that push from your #1. I actually had it happening two places. In one, a DataArray had a "coordinates" attribute referring to coordinates that weren't present in the DataArray and in the other, a DataArray had an "ancillary_variables" attribute referring to other variables that weren't present. In both cases, they weren't present once I had subsetted down to a DataArray from the greater Dataset (but were in the full Dataset). Thank you!

**Comment by kthyng** [comment]
I have a new variation of this one:

```
WARNING - /Users/kthyng/miniconda3/envs/omsa/lib/python3.10/site-packages/cf_xarray/accessor.py:1642: UserWarning: Variables {''} not found in object but are referred to in the CF attributes.
```

No variables specified! So I'm not sure how to get rid of it, but I am also pretty tired of the warning. Does this not happen to other people as frequently as me?

**Comment by dcherian** [comment]
You can set `warn_on_missing_variables=False`: https://cf-xarray.readthedocs.io/en/latest/generated/cf_xarray.set_options.html

We really should document this (maybe in the FAQ?)

> Variables {''} not found in object

Do you have an attribute with an empty string in it?

**Comment by kthyng** [comment]
Ok thank you, I will set this. I'm working with multiple models so it is hard to track down small differences in attributes. As long as the basics work with cf-xarray, I'm set. Thank you!
