### ISSUE TITLE
roadmap and goals

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#30]
I took a stab at defining the scope of this project here: https://cf-xarray.readthedocs.io/en/latest/roadmap.html

It would be good to get input on this.

**Comment by andersy005** [comment]
Thank you for putting this together, @dcherian! 

> This package will not provide a full implementation of the CF data model using xarray objects. This use case should be served by Iris.

I am wondering if this point can be expanded to clearly state where the lines between `cf-xarray` and `iris` are drawn? I am asking this mostly for people like myself who haven't used iris before (this also includes people who are not familiar with iris at all).

**Comment by dcherian** [comment]
It's hard to write down.

For example. Iris has all these coordinate types corresponding to CF auxiliary coordinate definitions: https://scitools.org.uk/iris/docs/latest/iris/iris/coords.html . cf_xarray is not going to implement special subsets of xarray's `Coordinates` to do that.

The focus is more on *interpreting* CF attributes for convenient analysis, and in some cases adding some computations that interpret those attributes (your bounds-aware resampling for example).
