### ISSUE TITLE
pypi maintainers

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#362]
Somehow I'm the only one wiht pypi priveleges.

@kthyng @aulemahal @malmans2 could you reply wiht your PyPI and RTD usernames please? Mattia, you're already on the RTD list so I just need your pypi name

**Comment by kthyng** [comment]
kthyng across the board!

**Comment by aulemahal** [comment]
I log in to RTD using github, so "aulemahal".
Pypi: pascalbo
Thanks!

**Comment by malmans2** [comment]
My PyPI username is malmans2

**Comment by dcherian** [comment]
done. thanks all!
