### ISSUE TITLE
How to cite cf-xarray

### ISSUE THREAD

**Issue by BorjaEst** [xarray-contrib/cf-xarray#369]
Similar to [how-should-i-cite-xarray](https://docs.xarray.dev/en/stable/getting-started-guide/faq.html#how-should-i-cite-xarray), it would be nice to add into the FAQ the way to cite cf-xarray.

**Comment by DWesl** [comment]
For those who know to look for it, [the main repository page](https://github.com/xarray-contrib/cf-xarray) has a "Cite this repository" drop-down with options for APA and BibTeX.  Better discoverability isn't a bad thing, though.
