### ISSUE TITLE
cf-xarray/data folder no longer packaged in wheel

### ISSUE THREAD

**Issue by Zeitsperre** [xarray-contrib/cf-xarray#415]
Hi there,

I noticed in some of my builds that cf-xarray was failing due to a data file that is now no longer present in the wheel: `data/cf-standard-name-table.xml`. Could it be that the file is being ignored in the Manifest?

Stack trace:
```
self = <xml.etree.ElementTree.ElementTree object at 0x7fb17b7dd910>
source = '/home/runner/work/RavenPy/RavenPy/.tox/py39-numpy/lib/python3.9/site-packages/cf_xarray/data/cf-standard-name-table.xml'
parser = None

    def parse(self, source, parser=None):
        """Load external XML document into element tree.
    
        *source* is a file name or file object, *parser* is an optional parser
        instance that defaults to XMLParser.
    
        ParseError is raised if the parser fails to parse the document.
    
        Returns the root element of the given source document.
    
        """
        close_source = False
        if not hasattr(source, "read"):
>           source = open(source, "rb")
E           FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/RavenPy/RavenPy/.tox/py39-numpy/lib/python3.9/site-packages/cf_xarray/data/cf-standard-name-table.xml'

/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/xml/etree/ElementTree.py:569: FileNotFoundError

**Comment by dcherian** [comment]
Hmmm... I did change MANIFEST.in but don't see how it removed that https://github.com/xarray-contrib/cf-xarray/commit/736dfda284824710b0fd4e4b27670798afacd6a9#diff-41d5a52589e0480be9c099d2bba7a8135b8b0d71bcbb8df3582a8df1c2295003

**Comment by dcherian** [comment]
Ah see #416

**Comment by Zeitsperre** [comment]
From PyPI:
![image](https://user-images.githubusercontent.com/10819524/215895650-1b33b785-9035-4d5d-bf02-48b60c07f53f.png)


I noticed that you recently moved to `pyproject.toml`. It's possible that the MANIFEST isn't being used. I noticed that as well when changing systems.
