### ISSUE TITLE
identify `rlon`/`rlat` as `X`/`Y`

### ISSUE THREAD

**Issue by larsbuntemeyer** [xarray-contrib/cf-xarray#425]
It would be useful if we could have `rlon`, `rlat` also be identified as the `X`, `Y` axis from the variable name, e.g., adding them to the regex here?

https://github.com/xarray-contrib/cf-xarray/blob/ce9cd5a303e7344d55f9f85d49892d498a9cfbf2/cf_xarray/criteria.py#L139

and maybe also add `grid_longitude` and `grid_latitude` to the `X`, `Y` criteria here?

https://github.com/xarray-contrib/cf-xarray/blob/ce9cd5a303e7344d55f9f85d49892d498a9cfbf2/cf_xarray/criteria.py#L97

**Comment by dcherian** [comment]
Are any of these always 1D? Maybe the projection coordinates are? 

Basically we think that `axis` varibales should be 1D coordinate variables. This provides an easy way to refer to dimensions, as opposed to nD coordinate variables, and that is useful for array analysis.

So we don't usually set `axis="X"` on `longitude` variables because they are frequently 2D.

See these discussions:
https://github.com/xarray-contrib/cf-xarray/issues/23
https://github.com/xarray-contrib/cf-xarray/issues/87

**Comment by larsbuntemeyer** [comment]
> Are any of these always 1D? Maybe the projection coordinates are?
Yes, the projection coordinates should always be 1D coordinates according to [Appendix F](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#appendix-grid-mappings). There are basically 3 standard names:

* `grid_latitude` / `grid_longitude` for rotated pole
* `projection_x_angular_coordinate` / `projection_y_angular_coordinate` for geostationary
* `projection_x_coordinate` / `projection_y_coordinate` for all others.

Actually the conventions explictily say, that they should be rectangular coordinates so they should be 1D. In the case of rotated pole, that's not explictily stated, but i have never encountered a dataset where `rlon`, `rlat` would be projection coordinates and not 1D.

> So we don't usually set axis="X" on longitude variables because they are frequently 2D.
Yes, i agree! The coordinates i would like to identifiy with axis="X" would be those of the native grid coordinates.

**Comment by larsbuntemeyer** [comment]
> If these are sometimes 2D, perhaps we only set them when they are 1D? See https://github.com/xarray-contrib/cf-xarray/issues/368 for that request

Yes, i agree, for `lon`/`lat` a test for 2D would make sense, i can really be ambiguous if not attributes are provided.

**Comment by larsbuntemeyer** [comment]
Just saw, that iris uses the same definitions to identify `X`/`Y`:
https://github.com/SciTools/iris/blob/9192442a8cfa0b30da07e4a9613d1dccb6c7a20d/lib/iris/util.py#L249-L260

**Comment by dcherian** [comment]
Metpy uses the projection coordinates for `X`. `Y`: https://github.com/Unidata/MetPy/blob/db8588f46eeccaf1a177df13230485960fe1135e/src/metpy/xarray.py#L48-L51
