### ISSUE TITLE
"Unit expression cannot have a scaling factor."

### ISSUE THREAD

**Issue by VeckoTheGecko** [xarray-contrib/cf-xarray#446]
I've been working with a dataset with units of "bar" and "amp hours". Looking through the [CF conventions on units](https://cfconventions.org/cf-conventions/cf-conventions.html#units), it mentions that the conventions use the same units that UDUNITS supports ([databases for units](https://docs.unidata.ucar.edu/udunits/current/#Database)). Since bar and amp hours aren't noted in these databases, instead opting for `100 kPa` and `3600 C` respectively, which seems to be valid in UDUNITS world .

When using cf_xarray with this, I get the pint error:
```
invalid units for variable 'variable': 100 kPa (attribute) (reason: Unit expression cannot have a scaling factor.)
```

**My questions:**  
- Is there support in cf_xarray for scaled/shifted units? (or is this some of the missing functionality hinted to in #225)
- Is this support planned in future?
- What would be a good work around? Doing a manual conversion from `<my_units>` to SI then quantifying? Registering extra quantities? (I am very new to the world of pint, and would greatly appreciate any links to helpful resources or a quick code snippet)

**Issue tracker searches I've tried**:  
- units
- Unit expression cannot have a scaling factor
- UDUNITS

**Comment by dcherian** [comment]
>  I believe pint is "missing" support for the "scaled", "offset". "logarithmic" and "grouped" string types. I

A PR adding this info to https://cf-xarray.readthedocs.io/en/latest/units.html would be very welcome!

> As for the "C" issue, indeed the unit registry of cf-xarray was imported from xclim where we chose to use it as an alternative of "°C". The reason was that, in our experience, this mistake was quite common. Or at least, that it was more common to see this typo than it was to see coulomb used in climate data..

I think overriding Coulomb does make sense for the Climate world. I haven't actually seen `"C"` or `"℃"` in the wild. `"degC"` is the most common one I've seen.

**Comment by VeckoTheGecko** [comment]
Thanks for the advice and quick responses @aulemahal and @dcherian ! I misunderstood the package thinking it had parity with UDUNITS. I've now solved my issue by switching to `bar` and `ampere_hour` which are supported.

For anyone else finding this, I found the following code useful to list all units in cf_xarray:
```py
from pint import application_registry as ureg
import cf_xarray.units

for unit in ureg:
    print(unit)
```
