### ISSUE TITLE
fix tests

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#47]
annoyingly some tests can fail depending on where they are in `test_accessor.py`

For example `test_dicts` fails if it is at the end of the file because `airds.lon.attrs == {}`. 

Sometimes this is an xarray bug (https://github.com/pydata/xarray/issues/4120). 

It would be good to track this down.

**Comment by kmpaul** [comment]
See comment on https://github.com/pydata/xarray/issues/4120.  If you globally set `keep_attrs=True`, the tests might work.

**Comment by dcherian** [comment]
Thanks for digging in to that.

>  If you globally set keep_attrs=True (xr.set_options(keep_attrs=True)), the tests might work.

Yes but it's nice that we're shaking out these bugs in xarray.

**Comment by kmpaul** [comment]
> Yes but it's nice that we're shaking out these bugs in xarray.

Yes!  Agreed. It does make me wonder, though, if `cf-xarray` should enforce `keep_attrs=True` globally, anyway. It seems like maintaining the attributes is necessary for reliable functionality.

**Comment by dcherian** [comment]
>  if cf-xarray should enforce keep_attrs=True globally, anyway. It seems like maintaining the attributes is necessary for reliable functionality.

I don't think we should set it but we could raise a warning at import time?

**Comment by kmpaul** [comment]
Wouldn't a user setting `keep_attrs=False` globally *break* CF-Xarray, since CF-Xarray depends on the attributes?

**Comment by jthielen** [comment]
> Wouldn't a user setting `keep_attrs=False` globally _break_ CF-Xarray, since CF-Xarray depends on the attributes?

Somewhat, if no operations are applying that strip attributes (such as a simple read-and-plot workflow), then everything should be fine.

**Comment by kmpaul** [comment]
> > Wouldn't a user setting `keep_attrs=False` globally _break_ CF-Xarray, since CF-Xarray depends on the attributes?
> 
> Somewhat, if no operations are applied that strip attributes (such as a simple read-and-plot workflow), then everything should be fine.

Then I would think a warning would suffice.  Unless we get lots of complaints from people saying manually setting `keep_attrs` all the time is annoying.
