### ISSUE TITLE
`.cf` accessor must be used first in chained calls

### ISSUE THREAD

**Issue by phil-blain** [xarray-contrib/cf-xarray#529]
Hi, thanks for this excellent package.

I'm not sure if this is working as designed or not, but this does not work:
~~~python
[1] masked.weighted(weights).cf.sum(dim=['X', 'Y'])
AttributeError: 'DataArrayWeighted' object has no attribute 'cf'
~~~
where `masked` and `weights` are DataArrays.

However, putting the `.cf` accessor first works:
~~~python
[1] masked.cf.weighted(weights).sum(dim=['X', 'Y'])
~~~

**Comment by dcherian** [comment]
Yes that is how it is implemented. It's not possible to make your first call work, I don't think.

**Comment by phil-blain** [comment]
OK, thanks for the quick answer!
