### ISSUE TITLE
no html reprs in rendered docs

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#57]
https://cf-xarray.readthedocs.io/en/latest/examples/introduction.html

Not sure why.

**Comment by benbovy** [comment]
It looks like bootstrap 4 (used by sphinx-book-theme) forces all html elements with `hidden` attributes to be actually hidden ([source](https://github.com/twbs/bootstrap/blob/adf4567386bbc6a16f37d336206ec51e32fdbfc3/scss/_reboot.scss#L616)), so the hack in https://github.com/pydata/xarray/pull/4053 does not work here (the result is even worse).

I guess that a workaround would be to add some custom CSS such as ``.xr-wrap { display: block !important }, assuming that custom CSS is loaded after Bootstrap's CSS. Not ideal, though, it looks like a hack on top of another hack.

**Comment by dcherian** [comment]
Thanks @benbovy . I've opened an issue at xarray for more discussion & visibility

**Comment by dcherian** [comment]
Fixed upstream: https://github.com/executablebooks/sphinx-book-theme/issues/238 https://github.com/pandas-dev/pydata-sphinx-theme/issues/274 https://github.com/pandas-dev/pydata-sphinx-theme/pull/275
