### ISSUE TITLE
Support groupby's datetime accessor behaviour

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#6]
```
ds.cf.groupby("T.month") → ds.groupby("time.month")
```

**Comment by dcherian** [comment]
@jukent @kmpaul This is more complicated than I thought because it will be the first time `cf_xarray` will use two "mappers" for a key. 

The easier steps are
1. Write a function that rewrites `"T.month"` to `"time.month"`. We can use `_get_axis_coord_single` to figure out the right translation.
2. Insert that function in this tuple: https://github.com/xarray-contrib/cf-xarray/blob/be4b4a55fd4dcce6d6a1fe5a5780fd79a31b416e/cf_xarray/accessor.py#L293

The challenge is that we will have to fix this piece (that I did not think hard enough about): https://github.com/xarray-contrib/cf-xarray/blob/be4b4a55fd4dcce6d6a1fe5a5780fd79a31b416e/cf_xarray/accessor.py#L643-L656

The list comprehension just loops over multiple mappers so `newvalue` will look like `[["T.month"], ["time.month"]]` (first element  from `_get_axis_coord_single` and second element from this new function). Instead we want to recursively apply mappers so that the new function rewrites the results of `_get_axis_coord_single` (the first mapper). Then `newvalue` should be `[["time.month"]]`. This will then get unpacked properly and passed on to `.groupby` as `"time.month"`.

A similar logic fix will be needed here: https://github.com/xarray-contrib/cf-xarray/blob/be4b4a55fd4dcce6d6a1fe5a5780fd79a31b416e/cf_xarray/accessor.py#L630-L637 but we can defer this until we find a need for it.

**Comment by dcherian** [comment]
Point taken! #58 should fix the more complicated part. Now we just need 1. and 2. which should be an easier lift.

**Comment by kmpaul** [comment]
@dcherian Thanks for doing the groundwork on this.  That was kind of you.  Consider the rest ours!

**Comment by jukent** [comment]
@dcherian 

What we have written as our new function is :

```
def _get_axis_coord_alt(var, key):
    if '.' in key:
        key, ext = key.split('.',1)
        
        results = _get_axis_coord_single(var, key)
        return [v + '.' + ext for v in results]
    
    else:
        return []

```

where we edit the `group` value in `_DEFAULT_KEY_MAPPERS` to 
```
"group": (_get_axis_coord_single,_get_axis_coord_alt,),
```

and it works!

We are struggling to come up with a function name for it because we aren't sure what the notation "time.month" is called.

**Comment by dcherian** [comment]
woot!

let's call it `_rewrite_groupby_time_accessor`
