### ISSUE TITLE
warn at import time if xr.core.options.OPTIONS["keep_attrs"] is False

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#77]
Maybe say something like 

> "cf_xarray works best when xarray keeps attributes by default. Please run `xr.set_options(keep_attrs=True)`"

This may be annoying though. We should definitely mention this in the docs (#73)

**Comment by jthielen** [comment]
I think it would be good to include the warning, but perhaps give the option to disable it with a cf-xarray option or environment variable if the user wants `keep_attrs` to be `False`.

**Comment by dcherian** [comment]
but you can't set a cf_xarray option without importing it first which would show a warning ;)

to be clear, this warning will only be shown once at import time not on every operation.

**Comment by jthielen** [comment]
> but you can't set a cf_xarray option without importing it first which would show a warning ;)
> 
> to be clear, this warning will only be shown once at import time not on every operation.

Ah, so an environment variable it would have to be!

**Comment by dcherian** [comment]
turns out the default is `"default"` so we could also only raise the warning is `OPTIONS["keep_attrs"] == "default"`. So we wouldn't bug anyone who has explicitly opted out of `keep_attrs`

**Comment by jthielen** [comment]
> turns out the default is `"default"` so we could also only raise the warning is `OPTIONS["keep_attrs"] == "default"`. So we wouldn't bug anyone who has explicitly opted out of `keep_attrs`

Even better!

**Comment by dcherian** [comment]
One (minor) issue with implementing this is that linters will format code to something like

``` python
import cf_xarray  # will raise warning here.
import xarray

xr.set_options(keep_attrs=True)
```

making the warning useless.
