### ISSUE TITLE
Keep cf metrics after a cf-xarray-wrapped function call

### ISSUE THREAD

**Issue by kthyng** [xarray-contrib/cf-xarray#92]
I would like to use cf-xarray to do something like a mean and then continue to use cf-xarray with another function call like resampling. However, the data array seems to lose connection with the remaining Axes. 

![image](https://user-images.githubusercontent.com/3487237/94204924-ceb17d80-fe87-11ea-94bb-a8bfb173a6a8.png)

In this case, temp isn't connected with the remaining Axes "T" after the mean operation, though its coordinate `ocean_time` still have the attribute `axis=T`.

![image](https://user-images.githubusercontent.com/3487237/94205103-25b75280-fe88-11ea-840f-1a497d1dc71e.png)

**Comment by dcherian** [comment]
This should work and I can't reproduce. Nothing is cached and it looks for the attrs every time you use `.cf` so this really should just work.
![Uploading image.png…]()

**Comment by kthyng** [comment]
Ok this demonstrates the problem:

```
loc = 'http://barataria.tamu.edu:8080/thredds/dodsC/forecast_latest/txla2_his_f_latest.nc'
ds = xr.open_dataset(loc, chunks={'ocean_time': 1})
ds.ocean_time.attrs['axis'] = 'T'
ds.ocean_time.attrs['standard_name'] = 'time'
ds['temp'].attrs['coordinates'] = 'lon_rho lat_rho z_rho ocean_time'  # THIS IS THE PROBLEM LINE
ds.temp.cf.mean(['s_rho','eta_rho','xi_rho']).cf.describe()
```

When the `temp` attribute 'coordinates' are set like the noted line above, my problem happens. I had put that into xroms because I thought it was necessary. Commenting it out fixes the problem.

**Comment by dcherian** [comment]
![image](https://user-images.githubusercontent.com/2448579/94292007-e5b9a380-ff4b-11ea-80af-fe0cd2d16d09.png)


I think the last commit on this branch has fixed this. The `coordinates` attribute referred to variables `lon_rho, lat_rho, z_rho` that aren't associated with the dataarray. This would've raised an error that was silenced by describe.

**Comment by dcherian** [comment]
I mean the last commit on #90

**Comment by kthyng** [comment]
Ok, agreed. Thank you.
