### ISSUE TITLE
associating vertical coordinates with dataarrays in dataset in ROMS

### ISSUE THREAD

**Issue by kthyng** [xarray-contrib/cf-xarray#94]
I have updated to the newest stuff in github (so includes #90) but have the same problem as before: cf-xarray can find everything for Axes and Coordinates in the general Dataset, but I can't connect the z coordinates properly to individual DataArrays within the Dataset, as shown here with `temp` (no "vertical" coords). I have tried with and without adding the line:
`ds['temp'].attrs['coordinates'] = 'lon_rho lat_rho z_rho ocean_time'` to test with temp in particular but there is no difference in describe.

![image](https://user-images.githubusercontent.com/3487237/94297004-631fec80-ff29-11ea-8802-429df33f3151.png)

**Comment by dcherian** [comment]
Oh maximum annoyance.

`"coordinates"` is in encoding and it (being written by ROMS) doesn't mention `z_rho`. I'll fix now

**Comment by kthyng** [comment]
This is great! I can now get it to work by inputting the "coordinates" attribute for a variable in a dataset.

Is there a way that is easier to do this, now that this works? Currently I am writing up code to choose 4D variables and assign them a "coordinates" attribute with the appropriate lon, lat, z, and ocean_time coordinates. It would be great if I could just label the z coordinates that should "count" as coords for cf-xarray, and then magic happens in the background so they are recognized as such for each variable in the dataset that has that z_ variable attached as xarray coordinates.

(Note I do have more than 1 z_* coordinate for every variable because I also attached the non-time-varying version of the z coordinates to each variable, for convenience.)

**Comment by dcherian** [comment]
> then magic happens in the background so they are recognized as such for each variable in the dataset that has that z_ variable attached as xarray coordinates.

This would be the default if you didn't have `coordinates` in either `encoding` or `attrs` :D

If you have it in one, cf_xarray uses that to narrow down which to search for.

This is particularly necessary for POP output where all staggered variables are on `(nlon, nlat)` dims for no good reason
![image](https://user-images.githubusercontent.com/2448579/94303724-d2173880-ff5d-11ea-9ae3-65d72d7df851.png)

We want `popds.temp.cf["latitude"]` to give `TLAT` not `TLAT` and `ULAT` so the `coordinates` attribute must take precedence over `popds.temp.coords`

**Comment by kthyng** [comment]
Ah! Ok so I wasn't aware of encoding until you mentioned it recently. I am now removing 'coordinates' from all variables that have it in encoding and everything works (I think)!
