### ISSUE TITLE
Accessing unsupported coordinates returns an empty Dataset

### ISSUE THREAD

**Issue by malmans2** [xarray-contrib/cf-xarray#97]
I have a dataset with cell measures. Even if these coordinates are not supported, I'd like to keep them as coordinates in the dataset. The problem is that when I select these coordinates, `cf_xarray` returns an empty `Dataset` rather than a `DataArray`. Is this expected and I'm not supposed to have unsupported coordinates in the dataset?

Here is an example:
```python
import xarray as xr
import cf_xarray
import numpy as np
```

```python
x = 10
y = 20
ds = xr.Dataset(
    dict(
        lon=xr.DataArray(
            np.ones((x, y)),
            dims=("x", "y"),
            attrs=dict(standard_name="longitude"),
        ),
        lat=xr.DataArray(
            np.ones((x, y)),
            dims=("x", "y"),
            attrs=dict(standard_name="latitude"),
        ),
        area=xr.DataArray(
            np.ones((x, y)),
            dims=("x", "y"),
            attrs=dict(standard_name="cell_area"),
        ),
        var=xr.DataArray(np.ones((x, y)), dims=("x", "y")),
    )
)
ds = ds.set_coords(["lon", "lat", "area"])
```

```python
ds.cf.describe()
```

    Axes:
    	X: []
    	Y: []
    	Z: []
    	T: []
    
    Coordinates:
    	longitude: ['lon']
    	latitude: ['lat']
    	vertical: []
    	time: []
    
    Cell Measures:
    	area: unsupported
    	volume: unsupported
    
    Standard Names:
    	cell_area: ['area']
    

```python
# Area: Empty Dataset
print(ds.cf["cell_area"])
```

    <xarray.Dataset>
    Dimensions:  (x: 10, y: 20)
    Coordinates:
        area     (x, y) float64 1.0 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0 1.0 1.0
    Dimensions without coordinates: x, y
    Data variables:
        *empty*

```python
# Longitude: OK, DataArray
print(ds.cf["longitude"])
```

    <xarray.DataArray 'lon' (x: 10, y: 20)>
    array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1.]])
    Dimensions without coordinates: x, y
    Attributes:
        standard_name:  longitude

```python
# How do I get the area values, for example to make a plot?
ds.cf['cell_area'].plot()
```

    ---------------------------------------------------------------------------

    ValueError                                Traceback (most recent call last)

    <ipython-input-6-d7689d33f907> in <module>
          1 # How do I get the area values, for example to make plot?
    ----> 2 ds.cf['cell_area'].plot()
    

    /noc/msm/scratch/climate/malmans/miniconda3/envs/overflows/lib/python3.7/site-packages/xarray/plot/dataset_plot.py in __call__(self, *args, **kwargs)
        160     def __call__(self, *args, **kwargs):
        161         raise ValueError(
    --> 162             "Dataset.plot cannot be called directly. Use "
        163             "an explicit plot method, e.g. ds.plot.scatter(...)"
        164         )

    ValueError: Dataset.plot cannot be called directly. Use an explicit plot method, e.g. ds.plot.scatter(...)

**Comment by dcherian** [comment]
@malmans2 this is a bug. More to do with indexing using a standard name when the variables is in `coords`. 

Can you see if #98 fixes it? Thanks for the great example.

PS: I'm excited you're using this!

**Comment by malmans2** [comment]
Yup, #98 fixes it.
Thanks a lot!
